### ISSUE TITLE
GUIfy  the app

### ISSUE THREAD

**Issue by boredsquirrel** [Lunarequest/sddm2rpm#5]
```
printf """[Desktop Entry]
Exec=sddm2rpm %f
GenericName[de_DE]=Wandle SDDM Tar-Archive in RPMs um
GenericName=Converts SDDM Tar Archive to RPM
Icon=preferences-system-login
MimeType=application/x-zstd-compressed-tar;application/x-xz-compressed-tar;application/x-tzo;application/x-tarz;application/x-tar;application/x-lzma-compressed-tar;application/x-lzip-compressed-tar;application/x-lz4-compressed-tar;application/x-lrzip-compressed-tar;application/x-compressed-tar;application/x-bzip-compressed-tar;
Name=SDDM2RPM
Type=Application""" > ~/.local/share/applications/sddm2rpm.desktop
```

Works great if you add ~/.cargo/bin to $PATH.

**Comment by boredsquirrel** [comment]
making it a dolphin extension would also work but clutter the menu more and for me its very weird and inconsistent to get them to even show.

**Comment by boredsquirrel** [comment]
didnt know where to put it, when using cradle it would not be included and putting it in the app would also be complicated? Just add it to the readme? your choice

**Comment by boredsquirrel** [comment]
here is a try to automatically convert .zip files

```
printf """[Desktop Entry]
Exec=unzip %f && tar -czvf %f.tar.gz %f && sddm2rpm %f.tar.gz
GenericName[de_DE]=Wandle SDDM Tar-Archive in RPMs um
GenericName=Converts SDDM Tar Archive to RPM
Icon=preferences-system-login
MimeType=application/zip
Name=SDDM2RPM
Type=Application""" > ~/.local/share/applications/sdm2rpm-zip.desktop
```

Weirdly it keeps the ".zip" ending on the files, otherwise works

**Comment by Lunarequest** [comment]
I personally do not think this would work atleast in this form for a GUI. If you do want zip support feel free to open a pr. you would need to change https://github.com/Lunarequest/sddm2rpm/blob/mistress/src/archive.rs to support zips. Afaik no one distributes sddm themes as zips. Which theme is shipped as a zip?

**Comment by Lunarequest** [comment]
zips are now supported

**Comment by boredsquirrel** [comment]
great work! I tried it but didnt find the time to learn everything.

Do you know any other use cases for this tool?

And did you know of microOSses transactional-update shell ? Maybe you dont even need these rpms there.

**Comment by Lunarequest** [comment]
When you use tu shell you are supposed to only use zypper. As for gui support the codebase prefers panic over returning results. Overall i don't see many people want a gui version of the tool
